### ISSUE TITLE
More plugins support

### ISSUE THREAD

**Issue by Julien-R44** [eslint-types/eslint-define-config#131]
So I'm currently rewriting my eslint config using your awesome plugin. And here are the plugins that are not supported for the moment: 

- https://github.com/eslint-community/eslint-plugin-promise
- https://github.com/mysticatea/eslint-plugin-eslint-comments
- https://github.com/SonarSource/eslint-plugin-sonarjs
- https://github.com/BenoitZugmeyer/eslint-plugin-html
- https://ota-meshi.github.io/eslint-plugin-jsonc/

Are you ok to add them? 
Should we just generate them automatically? I don't think I've seen a place where there are manually redigested types, but if the need arises, I'm okay with taking care of it.

**Comment by Shinigami92** [comment]
If adding them, please do a PR for each of them on it's own

**Comment by Shinigami92** [comment]
@Julien-R44 I had no success with eslint-plugin-html
The source code doesn't export rules and is written totally different than anything else

**Comment by Shinigami92** [comment]
with v2.0.0-beta.1 it is now possible to add support for any kind of eslint plugin
to see how types get generated, have a look at https://github.com/eslint-types/define-config-plugin-types/blob/main/scripts/generate-plugin-dts.ts
