### ISSUE TITLE
Improve generated comments

### ISSUE THREAD

**Issue by Shinigami92** [eslint-types/eslint-define-config#138]
Currently some comments are not generated very well:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/7195563/193850737-64a0a8c9-5aae-446e-9d5e-063293eb57f5.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/7195563/193850776-0378b5e4-3622-4fca-afe3-b51f18d694f0.png">

We should try to generate as few blank lines as needed or even don't generate empty JSDoc blocks.

Also we should add a test case for the functions that generates these comments.

**Comment by Dimava** [comment]
I've requested no-blank-blocks rule on https://github.com/gajus/eslint-plugin-jsdoc/issues/1042
So it may be possible to use eslint-plugin-jsdoc to cleanup unwanted `minItems` and empty `/* */` comments
