### ISSUE TITLE
Manually fix known ESLint schema mistakes

### ISSUE THREAD

**Issue by Dimava** [eslint-types/eslint-define-config#181]
Check out the list of known eslint schema bugs at https://github.com/eslint/eslint/issues/16879
> array-element-newline  
 nonblock-statement-body-position   
 no-sequences 
 no-constructor-return 

As we know that they are actual mistakes that won't be fixed anytime soon, it worth fixing them on our side

**Comment by Dimava** [comment]
#180

**Comment by Shinigami92** [comment]
I'm not quite sure how they should be corrected 🤔 
Would you like to open a PR for each rule separately and then I can generate and inspect the diffs?

So you should only alter the rule type file by hand manually
