### ISSUE TITLE
Support augmented global properties

### ISSUE THREAD

**Issue by Shinigami92** [eslint-types/eslint-define-config#233]
Vue has something like this: https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties

@antfu suggested to try out to support this, so plugin authors can define their own TypeScript definitions and `eslint-define-config` would then just use these.

So code in the specific plugin projects would look like this:

```ts
import type { DeprecationRuleConfig } from './rules/deprecation/deprecation';

declare module 'eslint-define-config' {
  interface Rules {
    /**
     * Do not use deprecated APIs.
     *
     * @see [deprecation](https://github.com/gund/eslint-plugin-deprecation)
     */
    'deprecation/deprecation'?: DeprecationRuleConfig;
  }
}
```

```ts
import type { AdjacentOverloadSignaturesRuleConfig } from './rules/typescript-eslint/adjacent-overload-signatures';
// ...

declare module 'eslint-define-config' {
  interface Rules {
    /**
     * Require that function overload signatures be consecutive.
     *
     * @see [adjacent-overload-signatures](https://typescript-eslint.io/rules/adjacent-overload-signatures)
     */
    '@typescript-eslint/adjacent-overload-signatures'?: AdjacentOverloadSignaturesRuleConfig;
    // ...
  }
}
```

**Comment by ST-DDT** [comment]
When this is explored, maybe it is time to move this library/feature to the eslint main repository. 🤔

**Comment by antfu** [comment]
That would be nice, especially now with the Flat Config users can alias plugins to have different prefixes, this would also such configs still provide type safety

**Comment by Shinigami92** [comment]
More context: https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation

**Comment by Shinigami92** [comment]
Started some first experiments, and it seems to work :rocket: 

![temp](https://github.com/Shinigami92/eslint-define-config/assets/7195563/3117c701-e39a-4a01-a906-219acea70bf1)
