### ISSUE TITLE
Types are not correct for native ESM modules and cannot be imported there

### ISSUE THREAD

**Issue by spence-s** [eslint-types/eslint-define-config#237]
https://arethetypeswrong.github.io/?p=eslint-define-config%401.23.0

It is impossible to import types correctly into a node.js project using 

"module": "node16",
"moduleResolution": "node16",

v1.20 is the last version that worked correctly

**Comment by spence-s** [comment]
I believe you just need to update the module in this tsconfig to Node16, I am happy to contribute this fix if it would be accepted. I think it would still work in the same way it does now, except it will also work in native node ESM environments where it does not now.

**Comment by Shinigami92** [comment]
Please check v1.24.1
Since v1.24 we switched from no process step to tsx bundle
So the dist content is now newly organized 

If this still happens please create a minimal reproduction that we can checkout to see the error
