### ISSUE TITLE
Missing build files

### ISSUE THREAD

**Issue by deraw** [eslint-types/eslint-define-config#242]
On version `1.24.0`, only the file `index.cjs` is present in the `dist` folder (see the [package content on npm](https://www.npmjs.com/package/eslint-define-config/v/1.24.0?activeTab=code)).
The files `index.js` and `index.d.ts` that are referenced in the `package.json` are not present.

**Comment by Shinigami92** [comment]
Yeah, whoops 😬 
I forgot to add that to files property in package.json

Could you open a PR?
A can do a hotfix release tomorrow (I'm on my phone right now)

**Comment by deraw** [comment]
> Yeah, whoops 😬 I forgot to add that to files property in package.json
> 
> Could you open a PR? A can do a hotfix release tomorrow (I'm on my phone right now)

Sure thing! #243
