### ISSUE TITLE
v1.24.1 prevents installing on node 16

### ISSUE THREAD

**Issue by satouriko** [eslint-types/eslint-define-config#244]
This version (commit https://github.com/eslint-types/eslint-define-config/commit/e23b186aee995d77ddf6b09737b924db40abba38#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L121) drops node 16 support and breaks our project, as we depends on @vue/eslint-config-airbnb-with-typescript that depends on eslint-define-config@^1.6.0.
We still need node 16 because of issue with webpack (https://github.com/webpack/webpack/issues/14532) :(
This breaking change seems unintentional and released with a patch version, is it necessary to drop node 16 support? Could we add back node 16 to the engines field and/or move the incompatible changes to a major version?

**Comment by sxzz** [comment]
What are you using package manager? Have you tried ` --ignore-engines` flag (yarn)?
See https://stackoverflow.com/a/45088032

**Comment by Shinigami92** [comment]
Oh by the way, if you can rely on webpack and NodeJS 16, you also don't need to update your eslint-define-config version and just pin it
