### ISSUE TITLE
CJS type declarations are not created

### ISSUE THREAD

**Issue by Lehoczky** [eslint-types/eslint-define-config#282]
When dual-publishing libraries, CJS and MJS bundles must have different .d.ts files. Currently there is only type declaration file, which is for the MJS bundle.

Checked with:
- https://arethetypeswrong.github.io/?p=eslint-define-config%402.1.0
- https://publint.dev/eslint-define-config@2.1.0

PR is coming with the fix:)

**Comment by Shinigami92** [comment]
These types are not required and it is just a warning that can be ignored.
It only makes sense if the types differ from each other, but the emitted types are almost always the same and so would only double the bundle size.

So unless you proof me wrong, I would like to reject this PR.

**Comment by Lehoczky** [comment]
'Mkay for me!
