### ISSUE TITLE
FlatESLintConfig does not support custom plugins

### ISSUE THREAD

**Issue by Dyskal** [eslint-types/eslint-define-config#293]
Hi,
I was trying to use `@eslint-types/typescript-eslint` with flat config but I found that the plugin field does not support type augmentation

In [`FlatESLintConfig`](https://github.com/eslint-types/eslint-define-config/blob/ea48f491f100f599775b840f9bc2e41daeb0d3c5/src/flat-config/index.d.ts#L50), it is:
```js
plugins?: Record<string, ESLint.Plugin>;
```
Contrary to the legacy config in which it extends from `LiteralUnion<keyof CustomPlugins>`

Could you add support for plugin augmentation in flat config to make typescript-eslint plugin type work?
Thanks

**Comment by Shinigami92** [comment]
I'm more thinking about to deprecate eslint-define-config and shift work and effort to `@typescript-eslint`'s config (https://github.com/typescript-eslint/typescript-eslint/discussions/8802#discussioncomment-9055908)

**Comment by Dyskal** [comment]
I haven't saw this discussion!
I'll keep an eye on it then, thanks
